apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pocket-namenode-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pocket-namenode
    spec:
      hostNetwork: true
      containers:
      - name: pocket-namenode
        image: anakli/pocket-namenode
        ports:
        - containerPort: 9070
#      - name: pocket-datanode-dram
#        image: anakli/pocket-datanode-dram
#        ports:
#        - containerPort: 50030
